---
title: "analysis 2"
output: html_document
---



```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(FactoMineR)
library(factoextra)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)

path <- "C:\\Users\\emduc\\Desktop\\Drive\\symphostage\\"
```


```{r}
environment_trait<- read.csv(file.path(path, "environment_trait.csv"),header = T, dec = ".", sep=",") %>%  mutate(Dawkins = as.factor(Dawkins))

bois <- environment_trait %>%  filter(!is.na(Branch_diameter)) %>%  
  mutate(Bark_investment = (Bark_thickness/Branch_diameter))

bois <-bois %>% dplyr::select(-Branch_diameter)

bois[,15:22] <- as.data.frame(scale(as.matrix(bois[,15:22]), center = TRUE, scale = TRUE))


data_standar<- read.csv(file.path(path, "data_standar.csv"),header = T, dec = ".", sep=",") %>%  mutate(Dawkins = as.factor(Dawkins))


```
# Dawkins 

```{r}
environment_trait %>% filter(!is.na(Dawkins)) %>% filter(!is.na(diameter)) %>% 
ggplot(aes(Dawkins, diameter, na.rm = TRUE))+
  geom_boxplot()+
   stat_compare_means(method = "anova", 
                     label.y = 90 , na.rm = TRUE) +
  stat_compare_means(method = "t.test", 
                     aes(label = ..p.signif..),
                     ref.group = ".all.",
                     label.y = 85 , na.rm = TRUE)+
  geom_hline(yintercept = mean(environment_trait$diameter), linetype = 2)
```
```{r}
tamere <- lm(diameter~Dawkins, data= environment_trait)
diam_HSD <- aov(tamere)
print(TukeyHSD(diam_HSD))
```


# Bois 

```{r}
acp.bois <- PCA(bois[,c("LT_mean", "Bark_infra_density","Bark_thickness", "Wood_infra_density", "SLA", "Chloro_content", "Area_exclude", "LMDC")], graph = F)
fviz_pca_biplot(acp.bois , axes = c(1, 2), label ="var", scaling =2, col.var = "contrib", col.ind = "grey")
fviz_screeplot(acp.bois, ncp=10)
```

```{r}
ggplot(bois, aes(Bark_thickness, Bark_investment))+
  geom_jitter()

summary(lm(Bark_thickness~Bark_investment, data=bois))
```

```{r}
pairs(bois[,c("Wood_infra_density", "diameter", "Bark_thickness", "Bark_infra_density", "SLA", "Area_exclude", "LMDC", "Chloro_content", "LT_mean")], lower.panel = panel.smooth, upper.panel = panel.cor)
```


# LT / parcelle 


```{r}
environment_trait %>%  mutate( n_parcelle = as.factor(n_parcelle)) %>%
  ggplot( aes(n_parcelle,LT_mean, fill = traitement))+
  geom_boxplot()+
    stat_compare_means(method = "anova", 
                     label.y = 525, label.x = 2) +
  stat_compare_means(method = "t.test", 
                     aes(label = ..p.signif..),
                     ref.group = ".all.",
                     label.y = 505)+
  geom_hline(yintercept = mean(environment_trait$LT_mean), linetype = 2)
```


```{r}
environment_trait %>%  mutate( n_parcelle = as.factor(n_parcelle)) %>%
  ggplot( aes(n_parcelle,diameter, fill = LT_mean))+
  geom_boxplot()+
    stat_compare_means(method = "anova", 
                     label.y = 80, label.x = 2) +
  stat_compare_means(method = "t.test", 
                     aes(label = ..p.signif..),
                     ref.group = ".all.",
                     label.y = 77)+
  geom_hline(yintercept = mean(environment_trait$diameter), linetype = 2)
```



```{r}
environment_trait %>%  mutate( n_parcelle = as.factor(n_parcelle)) %>%
  ggplot( aes(topo,LT_mean))+
  geom_boxplot()+
    stat_compare_means(method = "anova", 
                     label.y = 525, label.x = 2) +
  stat_compare_means(method = "t.test", 
                     aes(label = ..p.signif..),
                     ref.group = ".all.",
                     label.y = 505)+
  geom_hline(yintercept = mean(environment_trait$LT_mean), linetype = 2)

TukeyHSD(aov(lm(LT_mean~topo, data=environment_trait)))

```

```{r}
tab_topo = matrix(NA, ncol = 5, nrow = 16)
tab_topo <- as.data.frame(tab_topo)
names(tab_topo) <- c("parcelle","N_individual","freq_bottomland", "freq_slope", "freq_hilltop")
tab_topo[,1] <- 1:16
for(i in 1:16){
tab_topo[i,2] <- environment_trait%>% filter(n_parcelle == i) %>%  nrow

tab_topo[i,3] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(topo== "Bas fond") %>% nrow() / tab_topo[i,2] )*100

tab_topo[i,4] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(topo== "Pente") %>% nrow() / tab_topo[i,2])*100

tab_topo[i,5] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(topo== "Plateau") %>% nrow() / tab_topo[i,2])*100
}

tab_topo <-tab_topo %>% mutate( parcelle = as.factor(parcelle), freq_bottomland = as.integer(freq_bottomland) , freq_slope = as.integer(freq_slope), freq_hilltop = as.integer(freq_hilltop)) %>% 
  reshape2::melt(id = c("parcelle", "N_individual"), variable.name = "frequence") %>% 
  dplyr::select(-N_individual)
  #mutate(f_value = as.factor(value)) 

ggplot(tab_topo, aes(parcelle,value, fill= frequence))+
  geom_bar(stat = "identity")+
   geom_text(aes(label=value))
```


```{r}
environment_trait %>%  mutate( n_parcelle = as.factor(n_parcelle)) %>%
ggplot(aes(x=morphotype_field ,y = LT_mean)) +
  geom_boxplot()+
    stat_compare_means(method = "anova", 
                     label.y = 525, label.x = 2) +
  stat_compare_means(method = "t.test", 
                     aes(label = ..p.signif..),
                     ref.group = ".all.",
                     label.y = 505)+
  geom_hline(yintercept = mean(environment_trait$LT_mean), linetype = 2)

TukeyHSD(aov(lm(LT_mean~morphotype_field, data = environment_trait)))
```



```{r}
tab = matrix(NA, ncol = 5, nrow = 16)
tab <- as.data.frame(tab)
names(tab) <- c("parcelle","N_individual","freq_G", "freq_Sp1", "freq_SG")
tab[,1] <- 1:16
for(i in 1:16){
tab[i,2] <- environment_trait%>% filter(n_parcelle == i) %>%  nrow

tab[i,3] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(morphotype_field == "G") %>% nrow() / tab[i,2] )*100

tab[i,4] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(morphotype_field == "S") %>% nrow() / tab[i,2])*100

tab[i,5] <- (environment_trait%>% filter(n_parcelle == i) %>% filter(morphotype_field == "SG") %>% nrow() / tab[i,2])*100
}

tab %<>% mutate( parcelle = as.factor(parcelle), freq_Sp1 = as.integer(freq_Sp1) , freq_SG = as.integer(freq_SG), freq_G = as.integer(freq_G)) %>% 
  reshape2::melt(id = c("parcelle", "N_individual"), variable.name = "frequence") %>% 
  dplyr::select(-N_individual)
  #mutate(f_value = as.factor(value)) 

ggplot(df_cumsum, aes(parcelle,value, fill= frequence))+
  geom_bar(stat = "identity")+
   geom_text(aes(label=value))
```



```{r}
environment_trait %>%  filter(n_parcelle != "16") %>% 
  mutate( n_parcelle = as.factor(n_parcelle)) %>%
  mutate( n_carre = as.factor(n_carre)) %>%
  ggplot(aes(x=n_parcelle ,y =LT_mean, fill= n_carre)) +
  geom_boxplot()
```


```{r}
library(tidyverse)
library(scales)
# environment_trait2 <- read_csv("data/environment_trait2.csv")
Measures_Individuals2 <- read.csv(file.path(path, "Measures - Individuals.csv"),header = T, dec = ".", sep=",") %>% 
  dplyr::rename( n_parcelle = "Plot" , n_carre = "Subplot" , n_arbre = "Tree")

data <- left_join(environment_trait, Measures_Individuals2, by = c("n_parcelle" , "n_carre" , "n_arbre")) %>% 
  mutate( n_parcelle = as.factor(n_parcelle))

ggplot(data, aes(as.Date(data$Date, format = "%d/%m/%Y"), LT_mean, color = n_parcelle)) + 
geom_point() +
scale_x_date(labels = date_format("%b"))+
   geom_text(aes(label=n_parcelle))

  
```

```{r}
data %>% 
  select(Date, n_parcelle, LT_mean, SLA, LMDC, Chloro_content, Area_exclude) %>% 
  mutate( n_parcelle = as.factor(n_parcelle)) %>% 
  filter(SLA < 400) %>% 
  filter(!(LMDC < 0.17 |LMDC > 0.55)) %>% 
 filter(! Chloro_content < 40.5) %>% 
  reshape2::melt(id = c("Date", "n_parcelle"), variable.name = "Trait") %>% 
  ggplot(aes(as.Date(Date, format = "%d/%m/%Y"), value, col = n_parcelle)) +
  geom_point() +
  scale_x_date(labels = date_format("%b")) +
  facet_wrap(~Trait, scales = "free")
```


# topo / morphotype 

```{r}
panel.cor <- function(x, y, digits=2, prefix="", cex.cor) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y, use = "complete.obs", method = "spearman"))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste(prefix, txt, sep = "")
  if (missing(cex.cor)) cex <- 0.7 / strwidth(txt)

  test <- cor.test(x, y)
  # borrowed from printCoefmat
  Signif <- symnum(
    test$p.value, corr = FALSE, na = FALSE,
    cutpoints = c(0, 0.05, 0.1, 1),
    symbols = c("*", ".", " ")
  )

  text(0.5, 0.5, txt, cex = cex * r)
  text(.8, .8, Signif, cex = cex, col = 2)
}
```


```{r}
pairs(environment_trait[,c("topo","dem","alt_creek","morphotype", "morphotype_field")], lower.panel = panel.smooth, upper.panel = panel.cor)


```
#varcomp morphotype


```{r}
library(ape)
library(nlme)

varcomp_data <- read.csv(file.path(path, "varcomp_data.csv"),header = T, dec = ".", sep=",") %>% 
filter(SLA < 400) %>% 
filter(!(LMDC < 0.17 |LMDC > 0.55)) %>% 
 filter(! Chloro_content < 40.5) 

 

varcomp_data[,9:13] <- as.data.frame(scale(as.matrix(varcomp_data[,9:13]), center = TRUE, scale = TRUE))

```

9:13 trait 


```{r varcomp SLA}
varcomp.SLA<-varcomp(lme(SLA~1,
random=~1|n_parcelle/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
 plot(varcomp.SLA)
```

```{r varcomp LMDC}
varcomp.LDMC<-varcomp(lme(LMDC~1,
random=~1|n_parcelle/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```

```{r varcomp LT}
varcomp.LT<-varcomp(lme(LT_mean~1,
random=~1|n_parcelle/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```


```{r varcomp Area}
varcomp.Area<-varcomp(lme(Area_exclude~1,
random=~1|n_parcelle/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```

```{r varcomp chloro}
varcomp.Chloro<-varcomp(lme(Chloro_content~1,
random=~1|n_parcelle/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```



```{r varcomp resu }

varcomp_resu <- as.data.frame(cbind(varcomp.Area, varcomp.LDMC, varcomp.LT, varcomp.SLA, varcomp.Chloro))

  varcomp_resu <- varcomp_resu %>% mutate( niveau = rownames(varcomp_resu)) %>% 
    dplyr::rename(Area = "varcomp.Area", LT="varcomp.LT", LDMC = "varcomp.LDMC", SLA = "varcomp.SLA", Chloro = "varcomp.Chloro")
  
varcomp_resu$niveau <- factor(varcomp_resu$niveau, levels = varcomp_resu$niveau)    

varcomp_resu <- reshape::melt(varcomp_resu,  id=c("niveau")) %>% 
  mutate(value1 = as.integer(value*100)) %>% 
  mutate(niveau = as.factor(niveau)) %>% 
  mutate(sum.value = cumsum(value1))
  
```



```{r varcomp plot }
ggplot(varcomp_resu,aes(x = variable, y = value1, fill = niveau, order= niveau))+
  geom_bar(stat = "identity", position = "stack")+
  labs(title = "Variance component analysis", y = "fraction of the total variance explained
       by each scale (value*100) ", x= "functional trait")+
  scale_fill_brewer(palette="PiYG")+
   geom_text(aes(label = value1),position = "identity" )
```
### topo category





```{r varcomp sla 2}
varcomp.SLA2<-varcomp(lme(SLA~1,
random=~1|n_parcelle/topo/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```

```{r varcomp lmdc 2 }
varcomp.LDMC2<-varcomp(lme(LMDC~1,
random=~1|n_parcelle/topo/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```

```{r}
varcomp.LT2<-varcomp(lme(LT_mean~1,
random=~1|n_parcelle/topo/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```


```{r}
varcomp.Area2<-varcomp(lme(Area_exclude~1,
random=~1|n_parcelle/topo/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```

```{r}
varcomp.Chloro2<-varcomp(lme(Chloro_content~1,
random=~1|n_parcelle/topo/morphotype/n_arbre/n_feuille, data = varcomp_data ,na.action = na.omit),1)
```


```{r}

varcomp_resu2 <- as.data.frame(cbind(varcomp.Area2, varcomp.LDMC2, varcomp.LT2, varcomp.SLA2, varcomp.Chloro2))

  varcomp_resu2 <- varcomp_resu2 %>% mutate( niveau = rownames(varcomp_resu2)) %>% 
    dplyr::rename(Area = "varcomp.Area2", LT="varcomp.LT2", LDMC = "varcomp.LDMC2", SLA = "varcomp.SLA2", Chloro= "varcomp.Chloro2") 
  
varcomp_resu2$niveau <- factor(varcomp_resu2$niveau, levels = varcomp_resu2$niveau)    

varcomp_resu2 <- reshape::melt(varcomp_resu2,  id=c("niveau")) %>% 
  mutate(value1 = as.integer(value*100)) %>%  
  mutate(niveau = as.factor(niveau))
  

```


```{r}
ggplot(varcomp_resu2,aes(x = variable, y = value1, fill = niveau, order= niveau))+
  geom_bar(stat = "identity", position = "stack")+
  labs(title = "Variance component analysis", y = "fraction of the total variance explained
       by each scale (value*100) ", x= "functional trait")+
  scale_fill_brewer(palette="PiYG")
```



```{r}
D.varcop2 <- as.data.frame(rbind(varcomp.Area2, varcomp.LDMC2, varcomp.LT2, varcomp.SLA2, varcomp.Chloro2)) 

pca.varcomp2 <- PCA(D.varcop2, graph= T)

fviz_pca_biplot(pca.varcomp2 , axes = c(1, 2), scaling =1, repel = TRUE)
```

```{r}
varcomp_resu %>%  filter(niveau == "n_arbre")

```

```{r}
varcomp_resu2 %>%  filter(niveau == "n_arbre")
```



# coefficient of variation 

```{r}
CV <- function(mean, sd){
      (sd/mean)*100
      }
```

```{r}
mean_data <- environment_trait %>% 
  dplyr::select( SLA, LMDC, LT_mean, Chloro_content, Area_exclude) %>% 
  mutate(leaf_area = log10(Area_exclude)) %>% 
   summarize_at(c("SLA", "LMDC", "LT_mean", "Chloro_content", "Area_exclude", "leaf_area"), mean, na.rm = T)

sd_data <- environment_trait %>% 
  dplyr::select( SLA, LMDC, LT_mean, Chloro_content, Area_exclude) %>% 
  mutate(leaf_area = log10(Area_exclude)) %>% 
   summarize_at(c("SLA", "LMDC", "LT_mean", "Chloro_content", "Area_exclude", "leaf_area"), sd, na.rm = T)

cv_data <- CV(mean = mean_data , sd= sd_data)
```





