---
title: "Branch data test"
output: 
  html_document:
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---
# document settings

```{r doc settings,  package, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = T, cache = T, message = F, warning=F)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(dplyr)
library(plotly)
```

# document cleaning 

```{r doc cleaning}
rm(list = ls()) ; invisible(gc());graphics.off()
path <- getwd() # path to all data files currently in the same place
# path <- file.path(getwd(), "data") # just a suggestion if you want to organise your data elsewhere like in a data subfolder
```

# data 

```{r data}
densite <- read.csv(file.path(path, "densite sympho.csv"),header = T, dec = ",", sep=";")
Dawkins <- read.csv(file.path(path, "Measures - Individuals2.csv"), header = T, dec=",", sep=";")
paracou <- read.csv(file.path(path, "Symphonia_Paracou.csv"),header = T, dec = ",", sep=";")
guyafor <- read.csv(file.path(path, "Symphonia_Guyafor.csv"),header = T, dec = ",", sep=",")
```

## index creation  

Index (Parcelle_Carre_Numero) cration for densite table.

```{r densite data index }
densite %<>% 
  mutate(Index = paste(Parcelle, Carré, Numéro, sep="_")) %>% 
  filter(Bois != "")
```

Index creation for dawkins table and NA removale.

```{r dawkins index}
Dawkins %<>% 
  mutate(Index = paste(Parcelle, Carre, Numero, sep="_")) %>% 
  filter( Dawkins != "") %>% 
  filter(Bois == "1")
```

Index creation for paracou  table.

```{r paracou index}
paracou %<>%  
  mutate(Index = paste( n_parcelle, n_carre, n_arbre, sep="_")) %>% 
  mutate(diametre = (circonf/ pi)) 
```

Index creation for guyafor table 

```{r}
guyafor %<>%  
  mutate(Index = paste( n_parcelle, n_carre, n_arbre, sep="_")) %>% 
  mutate(diametre = (circonf/ pi))
```

### unic data table 

```{r}
Final <- guyafor %>%
  filter((campagne == "2015")) %>% 
  filter(Index %in% densite$Index) 
```

48 individual in common for campagne 2015 but only 24 for 2016

```{r}
Final2 <- paracou %>%
  filter((campagne == "2015")) %>% 
  filter(Index %in% densite$Index) 
```

48 individual in common for campagne 2015 but only 24 for 2016

```{r}
final3 <- Dawkins %>% 
  filter(Index %in% densite$Index) 
```

```{r}
success <- merge(densite,Final2, by = "Index")

success2 <- merge(success, Dawkins, by = "Index")
```

```{r}
ggplot(success2, aes(x = diametre, y=Idbois, color = Dawkins, size = IDEcorce ))+
  geom_point(na.rm=T)
```

```{r}
ggplot(success2, aes(x= IDEcorce, y= Idbois))+
  geom_density2d()
```

