---
title: "Chloro_model"
output: html_document
---
# option 
```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

library(dplyr)
library(ggplot2)
library(car)

path <- "C:\\Users\\emduc\\Desktop\\Drive\\symphostage\\"
```

```{r}
data_standar <- read.csv(file.path(path, "data_standar.csv"),header = T, dec = ".", sep=",")%>%  mutate(Dawkins = as.factor(Dawkins))

soil_data <- read.csv(file.path(path, "envi_soil.csv"),header = T, dec = ".", sep=",")%>%  mutate(Dawkins = as.factor(Dawkins))
```



## chloro content

```{r chloro model 1 }
chloro_model <- lm(Chloro_content~ Dawkins + LT_mean + LMDC + +Area_exclude + wetness + d_creek + diameter + d_gap + lBAL +   diameter:lBAL + diameter:d_gap + wetness:diameter + d_creek:diameter, data = data_standar)

summary(chloro_model)
```

```{r chloro model 2}
chloro_model <- lm(formula = Chloro_content ~ Dawkins + LT_mean + LMDC + wetness +  d_creek + lBAL + diameter,
    data = data_standar)

summary(chloro_model)
```

```{r}
par(mfrow = c(2,2))
plot(chloro_model)
```
```{r}
step_data <- data_standar %>%  dplyr::select(-X, -n_parcelle, -n_carre, -n_arbre,  -SLA, -ID)

Chloro_full <- lm(formula = Chloro_content ~., data = step_data)

step(Chloro_full, data = step_data , direction = "backward")
```

```{r}
summary(lm(formula = Chloro_content ~ Dawkins + wetness + lBAL + d_creek + 
    diameter + LT_mean + LMDC, data = step_data))
```
# model with C and P 

```{r }
step_data <- soil_data %>%  dplyr::select(-X, -n_parcelle, -n_carre, -n_arbre,-alt_creek, -dem,  -SLA) %>% filter(!is.na(Dawkins))

Chloro_full <- lm(formula = Chloro_content ~., data = step_data)

step(Chloro_full, data = step_data , direction = "backward")
```

```{r}
summary(lm(formula = Chloro_content ~ Dawkins + Carbonmean + wetness + 
    lBAL + d_creek + d_gap + LMDC, data = step_data))
```

